require conf/machine/qemux86-64.conf

MACHINEOVERRIDES =. "qemux86-64:"
KMACHINE = "qemux86-64"

MACHINE_FEATURES:remove = "alsa bluetooth touchscreen"

KERNEL_FEATURES += "features/security/security.scc"

IMAGE_FSTYPES += "iso"
