BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "stegos"
BBFILE_PATTERN_stegos = "^${LAYERDIR}/"
BBFILE_PRIORITY_stegos = "6"

LAYERSERIES_COMPAT_stegos = "wrynose"
