# Initialization Manager
INIT_MANAGER = "sysvinit"

# Removed Distro Features
DISTRO_FEATURES:remove = " systemd x11 wayland vulkan alsa pulseaudio"

# Added Distro Features
DISTRO_FEATURES:append = " virtualization seccomp"

require conf/distro/include/stegos-harden.inc

DISTRO = "stegos"
DISTRO_NAME = "stegOS"
DISTRO_VERSION = "0.1"

hostname:pn-base-files = "stegos"
