require conf/distro/defaultsetup.conf
require conf/distro/include/stegos-init.inc
require conf/distro/include/stegos-remove.inc
require conf/distro/include/stegos-docker.inc

DISTRO = "stegos"
DISTRO_NAME = "StegOS"
DISTRO_VERSION = "0.1"
