require conf/distro/include/stegos-init.inc
require conf/distro/include/stegos-remove.inc
require conf/distro/include/stegos-harden.inc
require conf/distro/include/stegos-docker.inc

DISTRO = "stegos"
DISTRO_NAME = "stegOS"
DISTRO_VERSION = "0.1"

hostname:pn-base-files = "stegos"
